# Include hook code here
require 'aegis/constants'
require 'aegis/has_role'
require 'aegis/normalization'
require 'aegis/permission_error'
require 'aegis/permission_evaluator'
require 'aegis/permissions'
require 'aegis/role'
require 'rails/active_record'
require 'rails/action_controller'
require 'rails/special_permission'
require 'aegis/permission_filter'
require 'generators/aegis_generator'
